### ISSUE TITLE
Acceleration of free falling object

### ISSUE THREAD

**Issue by mbratland** [openfedem/fedem-solvers#20]
Simulating position of free falling object. Position of object at initial rest is given by 0.5 * a * t^2. When calculating position in FEDEM, position is half of correct position. It looks like acceleration at initial step is 0.
Procedure is done as follows:
Creating Free Joint in (0.0 , 0.0 , 0.0) for both master and slave triad. Attach master to ground. Attach Generic Part to slave triad. Do not need to change mass of Generic Part. All DOFs for Free Joint set to Fixed, but Tz is free. Set Gravitation under Model Preferences to Z = -10. Set Integration algorithm under Solver (Advanced mode) to Standard Newmark integration without numerical damping. Set both Stop time and Time increment to 0.3. Plotting Position Z for Triad [2]. Value calculated at Time = 0.3 is -0.225. Correct value should be 0.5 * (-10) * 0.3^2 = -0.450. Using -allSecondaryVars+ in Additional Solver Options. Plotting Acceleration Z for Triad [2]. This shows acceleration at time = 0.0 to be 0, while acceleration at time 0.3 = -10.

**Comment by kmokstad** [comment]
The plotted response at the initial step (time=0.0) corresponds to the modelling configuration (unless Initial Equilibrium iterations has been used, then it will be the static equilibrium state at time 0.0). Therefore, it is correct that the acceleration is zero at time=0.0 with this setup, since the time integration then has not started yet.

The response that you get, with only half of the expected displacement in the first time step, is due to inconsistent initial conditions, which by default is zero velocity and zero acceleration in all DOFs. Clearly this is wrong for this free-falling object case. The correct would be to specify an initial acceleration of -10 as well. Otherwise, what you are simulating is an object floating in outer space in zero gravity, and then instantly teleported into a strong gravity field in the first time step.

Unfortunately, we lack the possibility to specify non-zero initial acceleration in the GUI (we only have a field for initial velocity). However, you can still obtain this by editing the model file. Just insert the following line within the FREE_JOINT object of the fmm-file:
```
INIT_ACCELERATION = 0 0 -10 0 0 0;
```
With this, you should see that you will get the correct displacement, and the plotted acceleration should be -10 also at t=0.0

**Comment by mbratland** [comment]
Thank you for the reply. It worked.
This would be a nice feature to have in the GUI or perhaps as a command line option in the Additional Solver Options.

**Comment by kmokstad** [comment]
Good. I opened a new issue in the GUI repository (openfedem/fedem-gui#46) for this matter. Feel free to comment further on that issue. Since the initial conditions have to be specified DOF by DOF, an Additional Solver Options solution would be cumbersome. Thereby closing this issue which relates to the solver only.
